### ISSUE TITLE
Clone task description and project name to current entry

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#1]
@pfiaux mentioned that it would be nice to clone the **description** and **project name** from an existing entry

**Comment by pfiaux** [comment]
Looking at the current setup you could easily set something like:

```
$scope.newEntryText = clickedTask.text;
$scope.newEntryProject = ''clickedTask.project;
```

However it's probably not the best idea to keep everything in the scope and 1 giant controller in the long term but that's a different topic.
