### ISSUE TITLE
Change "Manual time" to "Manual end time"

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#12]
I find the "Manual time" string used as label in the current timer form a bit confusing.

At first it feels like we should enter a duration to track additional time.

What about renaming it to "Manual end time"? I think it would be clearer.

**Comment by Cyclodex** [comment]
Of course. Thanks for this suggestion.

**Comment by Cyclodex** [comment]
Note: It will also update the text "What have you done" to reflect better, that it has nothing to do with the current last minutes of work:

![screen shot 2016-08-22 at 00 36 09](https://cloud.githubusercontent.com/assets/840929/17840231/7efd6a50-6800-11e6-8ddb-f66dcbe04157.png)
