### ISSUE TITLE
Implement day entries & project sum represented as time bar

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#15]
We came up with the idea of having a time bar.
Lets define something and implement it.

In a separate branch we can also start testing some cases or implementations.

Something like d3.js will probably make sense. (@pfiaux mentioned this)
- https://d3js.org/
- https://github.com/flrs/visavail

**Comment by davidsandoz** [comment]
You're gonna have to show me how to setup the project locally, notably regarding the database connection. You can also document that in the README, or you can activate the Wiki of the repository and start documenting there :-)

Regarding implementation of this feature, I would rather start simply with CSS animations. I think that for what we want that should be enough. What do you think @Cyclodex?

**Comment by Cyclodex** [comment]
# time bar

True we could start simply with some divs and CSS Styling

# How to open the project

Right now it should be still super easy.
1. Git clone it, or download it.
2. If you have PHPStorm you can simply open the `index.html` file from there, it will load the external files correctly from remote.
   - Alternatively you can open `index.html` from a webserver (I guess it should work with mamp etc). 

Looks like it does not work directly from "finder" or browser because of the `//` I use to choose automatically http or https.

So no need for you to know anything about Firebase connection (or you should not).
For the DB I will need to further restrict access before documenting more details.

If you still have issues, lets sync. (I have some domain restrictions only right now for Firebase access).

# UPDATE

Please see #17 for the new webpack implementation. Its now even easier to start up you local instance.

**Comment by Cyclodex** [comment]
![screen shot 2016-09-01 at 01 55 17](https://cloud.githubusercontent.com/assets/840929/18150472/35aa0f72-6fe7-11e6-8e39-cf4fc0626207.png)

**Comment by alesiom** [comment]
Wtf at 2 am?? O_o

**Comment by Cyclodex** [comment]
I will have to test at least 1 day before I push this to the live-cyclone hosting. Don't want to break the tool for others.

Everyone can test this running the webpack/BrowserSync build with `npm start` on your local workstation (with latest commit)

![screen shot 2016-09-07 at 00 17 52](https://cloud.githubusercontent.com/assets/840929/18293274/12d25914-7492-11e6-970b-0820622cb45b.png)
