### ISSUE TITLE
Move the config into a separate file

### ISSUE THREAD

**Issue by pfiaux** [Cyclodex/cyclone#16]
Currently the config is in the index.html since it has the firebase keys, would it be better to move it to a separate file and keep the keys out of the git repo?

For example: `public/config/config.js`

Then adding `public/config/config.js` to the git ignore file so it's not committed and creating a `config.example.js` with sample values that can be committed.

The config can be loaded via a script tag or could even be included as part of the webpack build depending on the setup. This could also make it easier to have multiple setups or firebase environments (dev/prod)

**Comment by Cyclodex** [comment]
@pfiaux please review my commit, and make sure you have the config file in your localhost setup. Thanks

**Comment by pfiaux** [comment]
Looks good, now you can for example even have a dev config locally and use a different database to not mess up the production data.

I have a copy of the current config for now. The last step is to remove the config from the repository, the file is ignored but it looks like you added it to get before you ignored it.

**Comment by Cyclodex** [comment]
You closed it, does it mean its okey ? I did not do anything else with the config yet.

**Comment by pfiaux** [comment]
Sorry yes it's OK
