### ISSUE TITLE
Setup raw-loader loader and refactor ConnectionCtrl into a component

### ISSUE THREAD

**Issue by pfiaux** [Cyclodex/cyclone#18]
I'd like to setup [raw-loader](https://github.com/webpack/raw-loader) for html templates in the web pack build which would allow moving some of the html to separate template files to break it up.

To use templates we need either directives, routes or components, since components is the most angular 2 friendly way I think converting one of the current controller into a component, the [official angular doc](https://docs.angularjs.org/guide/component) is a bit confusing, I would follow a style similar to Todd Motto's [style guide](https://github.com/toddmotto/angular-styleguide#components) (probably a bit different since we're not running ES6 we can't use the same syntax, if we want ES6 that's for a different issue but it would be cool too!)

I think the ConnectionCtrl would be a good target to test the setup because it's small. If it works for the connectionCtrl we can do it for other controllers as well. So basically I would:
- update the webpack config
- move the template into it's own file (like `connection.tpl.html`)
- create a component which wraps the template and the controller
- use the component in index.html

**Comment by pfiaux** [comment]
This would allow us to start splitting up index.html into multiple files.
@Cyclodex is it OK if try this on a branch?

**Comment by Cyclodex** [comment]
Yes of course. Sounds good! I started to update the libraries already, but still having some issues with angularfire and the authentication on firebase. I will also do this in a branch. Just go ahead.

**Comment by pfiaux** [comment]
This didn't work like I thought, but it still turned out good:
- I created 2 components and was able to remove the connectionCtrl
- I was not able to add the pullRequest here so it's in #26 

There's some example components now so it should be easy to create more for new features or refactor older features. Closing this as resolved, see #26.
