### ISSUE TITLE
Load all libraries with npm / webpack instead of cdn's

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#32]
We probably should change the loading of all the angular and other modules over the network (cdn's) to get loaded per npm and webpack.

Should we load it with bower ? I guess not, not to add an other layer of complexity...
@pfiaux Do you also think, npm / webpack is enough for loading all the libraries?

**Comment by pfiaux** [comment]
If you use webpack then npm should be good to load the libraries from. If you can't find them on NPM you could use bower or use a github link as an npm module too.

Once you install it with npm you can simply require them where you use them or in cyclone.js

**Comment by Cyclodex** [comment]
@pfiaux The package.json changes are in the commit before.

- https://github.com/Cyclodex/cyclone/commit/3490abbfc33ec3cd2644690d3036d4efefc20fb2

Its all in the branch:

- https://github.com/Cyclodex/cyclone/commits/libraries-loading

**Comment by Cyclodex** [comment]
This one was just released and is getting tested right now :)
Closing already for now.

We still need to check the authentication which is completely separate for now.

**Comment by Cyclodex** [comment]
Authentication is now also on webpack code.
