### ISSUE TITLE
Add a link to issues list

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#33]
To facilitate feedback, it would be great to have a *Feedback / Report issue* button, for instance in the footer, that brings directly to https://github.com/cyclodex/cyclone/issues

**Comment by Cyclodex** [comment]
Okey good point. But is the github link not already enough?
Just in case you don't know, the **version number** is linked to the **changelog** on github.

If you still think it would be worth a feedback link, I will think about it :)

**Comment by davidsandoz** [comment]
Ha, I actually didn't realize that there was a link. Then I suppose I might not be the only one ;-)

Also having a link with the text *Feedback / Report issue* is more inviting to do so.

But of course that's not a priority issue, just something nice to have.
