### ISSUE TITLE
Enable copying time for aggregated time slots

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#35]
There's currently no button to copy the time of aggregated time slots. That would clearly be useful.

P.S. : So yes @Cyclodex, I'm using this copy to clipboard feature ^^

**Comment by Cyclodex** [comment]
As written in my last commit, here the question we have to discuss / define:

> * Question: It would also make sense to mark the entries as done -> But how should we act if only some tasks are done? Should we still mark all as done, or better not touch the task states and only copy the time ?
>  * Difficult to not make it complex, for now it will mark all the tasks as done, as this is the behaviour you probably expect if 0 ticket is done yet in the group... just asking...
>  * I personally kind of don't really like it, because it makes you not able to copy the left over time, without marking all tasks complete. But I see the complexity (of UX) we add if I change this behaviour.

**Comment by davidsandoz** [comment]
Hmm, I think this issue should be closed and the discussion should happen in #34, which shouldn't have been closed. Am I right @Cyclodex?

**Comment by davidsandoz** [comment]
Ah no, sorry! I didn't realize #34 was actually implemented. Nice! ^^

**Comment by Cyclodex** [comment]
Yes it is ;) The discussion actually is a mix between these two requests yes. :) lets do it here because it is about the aggregate time.

**Comment by Cyclodex** [comment]
Closing this, if there is an issue with current implementation, open new task.
