### ISSUE TITLE
Clicking the copy time button will not save the entry as marked, only visually works

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#36]
The click on the "continued" tasks time works.
The single task time copy button, will only mark the entry as done, refreshing the page will show you that the entry change was not saved into the db.

Fix this issue :)

**Comment by davidsandoz** [comment]
Aaaaah, I thought I was crazy remembering marking an entry and finding out later it was not. Good to know I'm sane ^^
