### ISSUE TITLE
Implement new interface for improved grouping / timeline handling

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#45]
@davidsandoz & @alesiom made some proposals how an improved layout could look like

**Comment by davidsandoz** [comment]
Here's a mock-up 🙂 
I didn't remade the whole footer because nothing changes there.

Maybe we can first make some design iterations before going into development. Let see what two developers can come up with 😅 

![cyclone - tasks view](https://cloud.githubusercontent.com/assets/1535702/24837418/d5b06080-1d33-11e7-9bb6-e7b5f40268ee.png)

Let me know what you think @Cyclodex

**Comment by Cyclodex** [comment]
If I understand this view correctly, its a "Task" approach and has nothing todo with "Today" or a timeline.

So it would still show the entries from yesterday etc, correct? Its more like the "time"-tool from NI. But more advanced :)

It will make an impact on how we save the entries, because the current "Timeline" is focusing on 1 day, which here we would implement differently in firebase.
After some time, the **Done** part could get big, so maybe we need an archive, or the component here, just shows the **Done-tasks** from past 7 days or similar. Then we could have an other view , which lists all the **Done-Tasks** from the past _(optionally as not really a must have)_

**Comment by davidsandoz** [comment]
> If I understand this view correctly, its a "Task" approach and has nothing todo with "Today" or a timeline.
> 
> So it would still show the entries from yesterday etc, correct? Its more like the "time"-tool from NI. But more advanced 🙂 

I realize I forgot to put the date on the right of the top bar. That might have confused your interpretation.
So, no, the Task view would still be related to today and we could switch betweens days the same way we currently do. No way to group tasks between different days. I don't think that's something we need. The good practice is to always track your time the same day, so let's not make it easier to do it differently.

I guess this simplify development as well 😉

**Comment by Cyclodex** [comment]
True, it might be common for some people, but I am fine if we don't have to support this.
@davidsandoz : Can we share the source file still somewhere, would be cool to see how you made this mockup.

**Comment by davidsandoz** [comment]
Here it is: [Cyclone.xd.zip](https://github.com/Cyclodex/cyclone/files/1078533/Cyclone.xd.zip)
 

I made it with [Adobe XD](http://www.adobe.com/products/experience-design.html) 😊

**Comment by Cyclodex** [comment]
Here a screenshot of the current progress:

![cyclone - task overview](https://user-images.githubusercontent.com/840929/26963564-7e7b02ea-4ced-11e7-881d-2f6ebfc181d2.png)

**Comment by Cyclodex** [comment]
Further impacts to define / refine:

- [x] Refine BREAK block, this one is special and don't really need a "checkbox" or be presented very prominent

- [x] Split up tasks between **Open** and **Done**

- [x] Discuss **Delete** feature -> really needed ? Its a complex change behind and not easy to undesrstand for users

... more comming.

**Comment by alesiom** [comment]
Working on this.

Prototype of a long term vision (keeping the same colors/overall feel). 
https://invis.io/DMC3QSQKA#/238262628_Start

I'll create new tasks for each smaller feature, proposing a short term solution with the current Cyclone and a long term solution with the vision attached above.

**Comment by alesiom** [comment]
First tried with XD, but I'm too slow and still very limited. Switched to Sketch
[proposal_lex_001.sketch.zip](https://github.com/Cyclodex/cyclone/files/1065957/proposal_lex_001.sketch.zip)

**Comment by Cyclodex** [comment]
I finally have a staging, where you guys can test on a completely separate instance.
 * Code of my latest efforts of the grouping feature
 * DB / Data is completely separate! So we don't break live Data!
 * This also means that you need to register or link google account again

Have fun! And thanks for your contributions already.
 * https://cyclone-staging.firebaseapp.com

**Comment by Cyclodex** [comment]
For a simpler preview of how this might look, proposed by @alesiom in a first version:

Would be nice if some more people review, give feedback or suggestions.

![screen shot 2017-06-14 at 17 47 12](https://user-images.githubusercontent.com/840929/27141850-9c8b03ee-5129-11e7-8271-0cad13ae1eb2.png)

**Comment by davidsandoz** [comment]
Awesome @alesiom!

* The split feature is interesting, I already see situations where I would be using it.
* The "Switch to internal/external" icon is also nice. Although, It'd be nice that we can still change to any category. For instance, sometimes I switch some time slot to trust time. But if this can be done in the Timeline view, that's enough for me.

Aside from that I don't have much more say but that I like it very much 😃

**Comment by alesiom** [comment]
@davidsandoz thx for the feedback.
 * Good point about the switch. Currently I had in mind that we could use the drag and drop on the subtasks. My wish was to have anyway Break and Trust time in the "ongoing" at any time, even if nothing was tracked in there yet (see screenshot above). But your point raises the fact both features overlap a bit, so might not be optimal yet.

@Cyclodex & @davidsandoz if you have this view, would you still need to act on the timeline view, or could it be very reduced feature wise and rather focusing on displaying the timeline of the day? (I'm questioning the "need" of timeline to interact with the app) --> @alesiom create a new ticket to discuss this

**Comment by alesiom** [comment]
@davidsandoz 
 I actually have another question concerning your remark about switching. Would you switch a complete task (e.g. Kime - Ticket 375) or rather a sub task (e.g. Kime - Ticket 375 - html update). In the latter case, I believe the drag/drop solution would actually solve your problem whereas the "switcher" wouldn't. In the former case, the "switcher" would solve it better (much quicker).

Could you give me further details on what generally happens, in particular, how do you currently proceed when you change a tracked time that is in a group into trust time

**Comment by Cyclodex** [comment]
> if you have this view, would you still need to act on the timeline view, or could it be very reduced feature wise and rather focusing on displaying the timeline of the day? 

I think we need some kind of time line because its a simple representation of a day.
I am thinking about how we could simplify and change it, for me right now it looks like these options are around:
Also every entry of this cyclone-system needs to be editable for worst case.

These are the options I came up with until now:
1. The view is simplified and redesigned to match design as suggested above (simple table lines)
   *  The groups are removed from this view , because the **Task** will cover that
2. The view is removed, or at least available optional only.
   * However this would mean that we need a graphic like the **Tasks-graph** in the footer to show the timeline.
      * For sure simplified
      * Less colorfull / clearer
      * On click the full entry would be revealed and editable

![cyclone-possible-timeline-graph](https://user-images.githubusercontent.com/840929/27182012-1ff1b16e-51da-11e7-96e6-e9299c5df6ba.png)

However I still think a super simple table would be simpler to understand, (like the design you proposed)

**Comment by davidsandoz** [comment]
> Good point about the switch. Currently I had in mind that we could use the drag and drop on the subtasks. My wish was to have anyway Break and Trust time in the "ongoing" at any time, even if nothing was tracked in there yet (see screenshot above). But your point raises the fact both features overlap a bit, so might not be optimal yet.

I actually realize now that _Break_ and _Trust time_ don't have a _What_ or a _Task / Issue_ anymore, but just have _subtasks_. I suppose they cannot be marked as done neither. I think this makes completely sense. However, I'm just wondering how do I say if my current running timer is a break or trust time?
The fact that we can drag and drop _subtasks_ solves my issue indeed.

This new system is quite disruptive, but I think in a very good way 👍 

> if you have this view, would you still need to act on the timeline view, or could it be very reduced feature wise and rather focusing on displaying the timeline of the day? (I'm questioning the "need" of timeline to interact with the app)

For me, the current timeline view that appears at the bottom of the page is enough. I would then rather go for the option 2 that @Cyclodex suggests. It doesn't even need to be editable. I think we can change everything with the suggested task view.

However, this timeline could be hard to read if we have a lot of small time slots. A simple table as @Cyclodex suggests could be nice to have as well (non-editable)

> I actually have another question concerning your remark about switching. Would you switch a complete task (e.g. Kime - Ticket 375) or rather a sub task (e.g. Kime - Ticket 375 - html update). In the latter case, I believe the drag/drop solution would actually solve your problem whereas the "switcher" wouldn't. In the former case, the "switcher" would solve it better (much quicker).
> 
> Could you give me further details on what generally happens, in particular, how do you currently proceed when you change a tracked time that is in a group into trust time

As mentioned above, the drag and drop solves my problem 🙂 

----

Now I'm also wondering, about the merge feature. We are proposed to merge two subtasks with the same name, but this can only be done, if the two subtasks are next to each other right? Because if there is another subtask that was tracked in between, then the merge cannot happen as a subtask has a start time and an end time. Merging two subtasks that are not next to each other in the timeline makes it also difficult to represent in the timeline visualisation.

**Comment by alesiom** [comment]
> Now I'm also wondering, about the merge feature. We are proposed to merge two subtasks with the same name, but this can only be done, if the two subtasks are next to each other right? Because if there is another subtask that was tracked in between, then the merge cannot happen as a subtask has a start time and an end time. Merging two subtasks that are not next to each other in the timeline makes it also difficult to represent in the timeline visualisation.

Wrong, this is the "task" view, and for such, there is absolutely no concept about what really happens behind. In that sense, you could merge any subtasks, even if you do the first part in the morning and a later part in the afternoon. Of course, on the timeline, those would still be separate (but would now have the same name), but on the task page, it would be merged into only one, making it much simpler to now were is what task and what to track.

> timeline

Thx for both of your feedback. It was also my wish to keep it, but rather use it as a visual representation than use it do manage my entries.  I'll think about it and will come back with couple proposal based on your suggestions

**Comment by Cyclodex** [comment]
> merge feature

@davidsandoz I also asked this already in the invision prototype, so yes this is only visual. _(Otherwise would mess up timeline)_
@alesiom I competely see what you mean, you would be not interested in seeing "Doing XY" several times, its enough to have it once, with the complete time of all entries together.
Maybe we should not ask "merge it?" to make it simpler, just group them together.

![toggle grouping of same entry](https://user-images.githubusercontent.com/840929/27214008-6c6fdcd8-526a-11e7-9210-fdff119cdeaf.png)

and you can open it:
![toggle grouping of same entry open](https://user-images.githubusercontent.com/840929/27214249-b2269374-526b-11e7-8647-42203c23917d.png)


For an example we could show how many entries are counted together as it does in toggle:
* Optionally we could think of "showing all merged" entries if wanted, kind of what the current grouping on the right of timeline does.

**Comment by Cyclodex** [comment]
Is there still something critical missing to make this ticket as done for the moment?
We can still push feature into separate tickets, and check which ones are must haves and which ones are nice to have. Otherwise loosing focus for this release.

@davidsandoz would you help to identify still your missing features or functionality?
Please really think what is must have, and what are use specific wishes, but go ahead and create tickets! 👍 Thx

**Comment by davidsandoz** [comment]
Created #59 #60 and #61 🙂

**Comment by Cyclodex** [comment]
I am finally closing this issue, we are testing the new interface and requests should come in as issues / tickets. Thanks.
