### ISSUE TITLE
Allow standard input text field mouse interactions

### ISSUE THREAD

**Issue by renestalder** [Cyclodex/cyclone#48]
The default mouse interactions on the form fields are suppressed at the moment.

Example:

- Can't select text with the mouse cursor
- Can't select all text inside a form field with a double click

**Comment by Cyclodex** [comment]
I can not reproduce this, are you using some special plugins?

For me it works like on every other form:
 * Single click: put pointer there
 * Double click: Mark the word
 * Trible click: Mark the whole field

I tested this now on FF, Chrome and Safari without issues.

**Comment by renestalder** [comment]
Okay, I'm sorry. Further tested this in the mentioned browser. Seems like a very specific case to Vivaldi, when running a website inside a sidebar tab.
