### ISSUE TITLE
Unchecking a group doesn't work

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#49]
If you have several time slots grouped together and marked as complete, then the checkbox in the group "card" doesn't work to uncheck the whole group.

@Cyclodex: If it's not clear or you cannot reproduce, come to me so that I show you.

**Comment by Cyclodex** [comment]
Seems to be related to FF only. Works in chrome.

**Comment by Cyclodex** [comment]
Fixed issue in v.0.48 should work fine now.
