### ISSUE TITLE
Make date recognition more stable

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#52]
Glow reported that sometimes the timeline shows up old entries and switches back again.

Not sure what this could be, but I might to improve stability with changing some logic of how to load the screens.

* Maybe instead of just let it work on the current day, switch to the days path and only rely on this.
* This should also cover the case that when cyclone is still open from yesterday, that it should switch to the new day.
* Tricky might be the situation around midnight - but lets see - we are not working normaly at this time

**Comment by davidsandoz** [comment]
FYI, when loading the page for the first time of the day, I sometimes also have data from the day before in the current timer (Firefox).

**Comment by Cyclodex** [comment]
Now it happens that it jumps back to the time-tab, no idea why.
It somehow loads again the url one visited once.
I will have to remove this part and change the logic a bit. Not sure why angular is doing this.

**Comment by Cyclodex** [comment]
Basically, this feature changed completely, but still having issues with auto-switching the day. This will be handled separately as an enhancement.
However it should have reached a more stable way how we deal with the day (instead of "today")
