### ISSUE TITLE
Keep current timer data when switching view

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#53]
On the beta version in staging, with Firefox (didn't try other browser), if we have something entered in the current timer and switch view (between Time and Task), the data that was entered in the current timer is removed.

It would be expected that it stays.

**Comment by Cyclodex** [comment]
Know, but a feature i have to implement, thanks for ticket.

**Comment by Cyclodex** [comment]
Done and ready for beta testing. NOTE: **No** _"manual end time"_ support, as this has troubles all over the places. Should not be a big deal, as the time entry is not that often used.

Will create a new ticket for improving the time input overall.
