### ISSUE TITLE
A break should go directly into "Done"

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#54]
Currently, if I track a break, it goes in the "Open" tasks.

As we don't track time for a break, there is no reason to keep them in Open.

It would therefore be expected to have the breaks go directly in the Done section when we track them.

**Comment by Cyclodex** [comment]
Accept. What about trust time?

**Comment by davidsandoz** [comment]
Same thing as it is not tracked.

**Comment by Cyclodex** [comment]
What do you think, is the order of these elements?
I am unsure if they should be Alphabetically or related to some timestamp etc.

Can we define something? Best something which works for all the 3 lists:
 * Open
 * Done
 * Break / Trust

**Comment by davidsandoz** [comment]
I would order based on the end time of the last time slot (from most recent to oldest)

**Comment by Cyclodex** [comment]
Implemented, will test tomorrow and push to staging when ok.
