### ISSUE TITLE
Add continue button

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#59]
Currently the two buttons available have the following behaviors
1. Use this current project & description for current timer
1. Track current timer into this group

I suggest to replace the first one with this behavior and a "play" icon
* Log current timer and continue with this task

### Reason for this change

We have two types of users:
1. The one who fill time slot details right before logging it
2. The one who fill time slot details right after starting the timer

The two currents buttons are rather made for first type of user and the first button is actually redundant as clicking the second one does the same and in addition log the time slot.

The new suggested "continue button" would fit the need of the second type of user.

Let me know what you think @Cyclodex

**Comment by Cyclodex** [comment]
I completely understand, and have seen that we need to make some features possible to get disabled/enabled. So the user can decide which feature to use and setup his own tooling.

I already have something in mind, similar to the projects where one will be able to control this on his profile. I will need some time but definitely on my plan. Thanks for ticket.

**Comment by Cyclodex** [comment]
The continue button is back soon, at least when you really want it. The buttons are now features, which every user can enable/disable himself.
Will come out soon with the next release, trying to finish first the autocomplete, to have a full featured release :)
