### ISSUE TITLE
Re-introduce time stats

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#60]
In versions <0.50 a task-type repartition chart was visible at the bottom of the page and hovering it would show a one-line timeline and the projects repartition.

I suggest to re-introduce those charts in the latest versions of Cyclone.

Personally, the one I miss the most is the task-type repartition. Therefore if one has to prioritize, I would bring back this one first.

### Improvement suggestion

The task-type and project repartition charts do not necessarily need to be represented as long bar charts. This is mostly useful for the one-line timeline visualization.

For the task-type and project  charts, they could alternatively be represented as pie charts, for instance on the left side-bar. They would take much less space and the colors would be enough to know what they represent (at least for the task-type representation)

This is just an improvement suggestion and the priority should be put on bringing the already implemented charts.

**Comment by Cyclodex** [comment]
For later, maybe using something like this:
* https://www.highcharts.com/demo/pie-legend/grid-light
* https://www.highcharts.com/blog/tutorials/194-using-highcharts-with-angular-js/

**Comment by davidsandoz** [comment]
Hey @Cyclodex, thanks for the release 1.0.0!

I just wanted to say that this issue is still relevant for me, in case you have some time and need to figure out what to prioritize :-)

**Comment by Cyclodex** [comment]
Hey @davidsandoz, so you still want stats about projects or even tasks? Is the focus on daily, weekly or monthly time range ?

**Comment by davidsandoz** [comment]
What would be useful for me is stats about projects in the daily view 🙂
