### ISSUE TITLE
Add a new tab "Projects"

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#62]
That would be nice to have the possibility to set one own projects for auto-complete, but also to pre-define the matching type (internal/external).

This could be something to add to a new tab "Projects" on the side bar.

**Comment by Cyclodex** [comment]
Indeed, it would be a good starting point for having control over the projects.
I will use this to learn better how I should write components using ultimateangular course.

This is related to #50

**Comment by Cyclodex** [comment]
Coming soon but slightly different.
Instead of a "projects" tab, it will be part of the profile page.
Will be released when the autocomplete feature is also complete #50
