### ISSUE TITLE
Define feature "TODO" (Tasks in the future)

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#65]
# Idea
At some point I want to introduce TODO's where one can enter tasks to do.

More advanced could be setting a due date, or use the TODO's with time tracking.

**Comment by davidsandoz** [comment]
Wouldn't it be best to keep Cyclone scoped to time tracking?

There are already tons of todo apps out there and they're doing their job pretty well.

If you really want to do it and as long as it doesn't interfere with the time tracking part, I don't have a problem with that 🙂 

But I know for sure that I personally wouldn't use this feature.

Maybe that @alesiom @Mayeu or @renestalder would also have an opinion about this.

**Comment by Cyclodex** [comment]
Sure, no the goal would be definitely that it doesn't interfere with the "Timetracking" parts if one doesn't use it.

I completely understand your point, but also the same would go with "timetracking", so cyclone is not needed in fact :) I just try to make something which helps me better to manage my work days - not using 5 different tools, as I do now :) Thanks for the feedback so far!

**Comment by Cyclodex** [comment]
I quickly described the situation to @davidsandoz , but would like to address it also to @Mayeu (who came up with feedback internally), but also @alesiom, @renestalder etc.:
I will try to make an official (github)document to show up more what I am thinking of what "Cyclone" is for me, here a first try:

Further features will and should not break into others, they will only extend one or each others or work together with them.
If you think about the tooling of **Gitlab** for example, or **Github**, there are features one can use:

- commit code (git)
- use wiki pages for documentation
- use issues for creating tasks/tickets
- Manage issue in milestones or KANBAN and so on.
- Statistics of how active a user is
etc.

One is not need for an other feature to be used, but if you want you can combine to improve your productivity. So when I speak about such ideas like TODO, its rather a Task placed in the future.

If you don't care about your future, you don't need to use it, but if you do, and know there is an upcoming task you need to tackle, you could place it and later simple use it in the time part of cyclone.

My goal is to improve my productivity when working, and this just started with time-tracking, and went further into TASKS (the grouping we have), and might get into other topics as you now see.

PS: I know that what I am doing here is already existing somewhere. If one is happy and wants to use 5 different tools, I am complete fine with that. But I would like to challenge it (for myself) and try to create something more simpler/useful without having to switch applications or software. Also I am using this to improve my AngularJS skills, so this keeps me motivated in learning new things. :)

**Comment by Cyclodex** [comment]
Decision: Will keep it separate from cyclone, using some existing tools. (for now)
