### ISSUE TITLE
Define feature "Knowhow" section

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#66]
# Idea

I will define something like a **knowhow** database.
It will act and help one in regards of:
 * Links / Bookmarks (VS bookmark mess in browsers)
 * Hints / Notes (VS note tools, nvalt, evernote etc.)
 * Code snippets (like gists, nvalt)

This together with tags / categories, should make them quick searchable useful feature.

In addition, they could be "private" or "public" to share them or not.

**Comment by davidsandoz** [comment]
Same opinion as in #65. I think it'd be better to keep Cyclone focused on time-tracking.

But you decide 😉

**Comment by Cyclodex** [comment]
Thanks for your concerns, really ❤️ your contributions no matter if they would be 👍  or 👎 .
To clarify : This would be complete separate from the time tracking, if one doesn't want to use it, no need to. I guess I would even hide it from the navigation, if you don't want to use it.
So, it will not impact your time tracking experience.

**Comment by Cyclodex** [comment]
Decision: Will keep it separate from cyclone, using some existing tools.
