### ISSUE TITLE
Increase width of task input field

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#69]
In the logged items, the "Task / Issue" field is only 150px wide, which is quite small, notably on large screens. And there is a huge white space gap up to the right side of the bar where nothing is ever shown.

**Proposal**: Make the "Task / Issue" field take the whole space available in width.

**Comment by Cyclodex** [comment]
Done, thanks for the report.

**Comment by davidsandoz** [comment]
Awesome, thanks!
