### ISSUE TITLE
Add a favicon to get easy recognized

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#7]
We need to have a favicon so if the tab is pinned, one can better identify the cylone.
First iteration: Find something to put there.
We can later still make a own one / produce our self an icon.

**Comment by Cyclodex** [comment]
@alesiom Would you help to create an icon? Any ideas ?

**Comment by alesiom** [comment]
Oh you're too quick :P I had an idea for an icon, but didn't find the time yet to do it. I'll still propose it on this issue in case :)
