### ISSUE TITLE
Copy time into clipboard

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#8]
Try an easy way for copy the time to clipboard, keep it easy and simple as here : 
- https://css-tricks.com/force-selection-text-block/#article-header-id-8

We support what it will support, no crazy fallbacks will be implemented.

Also look into the selection, if we can improve this.
- https://css-tricks.com/force-selection-text-block/#article-header-id-0

**Comment by Cyclodex** [comment]
I think @pfiaux would love this feature ;)

**Comment by pfiaux** [comment]
The last time I looked at this (1-2 years ago) https://github.com/zeroclipboard/ZeroClipboard was a good way to access the clipboard. I think even github used zeroclipboard (at least it did at some point).

Today it looks like you can do it without flash using: https://github.com/zenorocha/clipboard.js/ but I'm not sure how good it works.

**Comment by Cyclodex** [comment]
Sounds good, we can give this a try. Do you want to start loading the library.
When its loadable, I can then check where to use and implement it (on the time-output actually)

Feel free to go ahead in a branch, thanks.

**Comment by Cyclodex** [comment]
@pfiaux : See my last commit , I started working on it.
