### ISSUE TITLE
Coping time from task view returns NaN

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#83]
From the *task view,* when marking a task as done, instead of copying the time (set to decimal in my case), I get NaN in my clipboard. It was even only for a 1-slot task.

This doesn't happen in the *time view*.

Aside from that, thanks for the great update 🙂

**Comment by Cyclodex** [comment]
Hello @davidsandoz , nice you received the update! Hope the rest works still for you, I try to not break your experience, even I have to add some new features for other usages :) (like these time format features)
I am sorry for the bug, the good news is, it is already fixed on the dev-branch, I will try to publish soon as possible an other update! Thanks for reporting the issue!

**Comment by davidsandoz** [comment]
Nice that you manage to create an interface that works for everyone ! I didn't notice anything else wrong. Thanks for fixing this bug 👍

**Comment by Cyclodex** [comment]
This is fixed and deployed with beta5 now. Have fun!

**Comment by davidsandoz** [comment]
Great! Thanks for the fix!
